routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@adminLogin')->name('dashboard');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'users', 'namespace' => 'User', 'as' => 'users.', 'middleware' => 'auth:web_admin'],
        function () {
            Route::get('/list', 'UsersController@list')->name('list');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::post('/store', 'UsersController@store')->name('store');
        });

    Route::group(['prefix' => 'logs/socialApps', 'namespace' => 'Logs\\SocialApps', 'as' => 'logs.socialApps.'],
        function () {
            Route::get('/telegram', 'Telegram\\TelegramErrorController@getUpdates')->name('telegram');
            Route::get('/message', 'Telegram\\TelegramErrorController@createMessage')->name('message');
            Route::post('/send', 'Telegram\\TelegramErrorController@sendMessage')->name('send');
        });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Address.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    protected $guarded =['address_id'];
}

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $guarded =['brand_id'];
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = ['category_id'];
}

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $guarded = ['comment_id', 'comment_like_count'];
}

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    protected $guarded =['coupon_id'];
}

app/Models/Filter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Filter extends Model
{
    protected $guarded =['filter_id'];
}

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $guarded=['image_id'];
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = ['order_id'];
}

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $guarded = ['payment_id'];

}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded =['post_id','post_like_count','post_view_count','post_share_count'];
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = ['product_id', 'product_like_count', 'product_view_count', 'product_share_count'];
}

app/Models/Send_method.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Send_method extends Model
{
    //
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
}

app/Models/Users/Admin.php
<?php

namespace App\Models\Users;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $primaryKey = 'admin_id';

    protected $guarded = 'admin_id';

    protected $hidden = ['admin_password', 'remember_token'];

    public function getAuthPassword()
    {
        return $this->admin_password;
    }
}

app/Models/Users/User.php
<?php

namespace App\Models\Users;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $primaryKey = 'user_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['user_id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'user_password',
        'remember_token',
    ];

    public function getAuthPassword()
    {
        return $this->user_password;
    }
}

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    //
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function start()
    {
        return view('admin.dashboard.dashboard');
    }
}

app/Http/Controllers/Admin/Logs/SocialApps/Telegram/TelegramErrorController.php
<?php

namespace App\Http\Controllers\Admin\Logs\SocialApps\Telegram;

use App\Services\ErrorReportingService\ToTelegramHandler\TelegramErrorHandler;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Telegram\Bot\Laravel\Facades\Telegram;

class TelegramErrorController extends Controller
{
    public function getHome()
    {
        return view('home');
    }

    public function getUpdates()
    {
        $updates = Telegram::getUpdates();
        dd($updates);
    }

    public function createMessage()
    {
        return (new TelegramErrorHandler())->getSendMessage();
    }

    public function sendMessage(Request $request)
    {
        return (new TelegramErrorHandler())->postSendMessage($request);
    }
}

app/Http/Controllers/Admin/User/UsersController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Requests\User\UserCreateFormRequest;
use App\Models\Users\User;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Services\User\UserCreatedService;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    private $userRepository;

    public function __construct(UserRepositoryInterface $repository)
    {
        $this->userRepository = $repository;
    }

    public function list()
    {
        $per_page = 10;
        $users = $this->userRepository->paginate($per_page)->getPaginator();
        return view('admin.users.list', compact('users'));
    }

    public function create()
    {
        $statuses = config('strings.user.statuses');
        $roles = config('strings.user.roles');
        $types = config('strings.user.types');
        return view('admin.users.create', compact('statuses', 'roles', 'types'));
    }

    public function store(UserCreateFormRequest $formRequest)
    {
        $newUserCreated = new UserCreatedService([
            'FullName' => $formRequest->FullName,
            'Email' => $formRequest->Email,
            'Username' => $formRequest->Username,
            'Mobile' => $formRequest->Mobile,
            'UserStatus' => $formRequest->UserStatus,
            'UserRole' => $formRequest->UserRole,
            'UserType' => $formRequest->UserType,
            'Password' => bcrypt($formRequest->Password)
        ]);
        if (!$newUserCreated->apply()) {
            return back()->with('errors', 'عملیات ثبت ناموفق بود!');
        }
        return redirect()->back()->with('success', 'کاربر جدید باموفقیت ثبت شد!');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('wrapper')
    <!--main content start-->
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        <p>
                            ثبت کاربر جدید
                        </p>
                    </header>
                    <div class="panel-body">
                        @include('partials.success')
                        @include('admin.users.form')
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
    <!--main content end-->
@endsection

resources/views/admin/users/form.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <strong>خطا: </strong>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <br>
        @foreach($errors->all() as $message)
            {{ $message }}<br>
        @endforeach
    </div>
@endif
<form action="{{ route('admin.users.store') }}" method="POST" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputFullName">نام کامل</label>
            <input type="text" name="FullName" class="form-control" id="inputFullName" placeholder="به فارسی تایپ کنید">
        </div>
        <div class="form-group col-md-6">
            <label for="inputUsername">نام کاربری</label>
            <input type="text" name="Username" class="form-control" id="inputUsername" placeholder="به انگلیسی تایپ کنید">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail">ایمیل</label>
            <input type="email" name="Email" class="form-control" id="inputEmail" placeholder="ایمیل معتبر">
        </div>
        <div class="form-group col-md-6">
            <label for="inputMobile">موبایل</label>
            <input type="number" name="Mobile" class="form-control" id="inputMobile" placeholder="موبایل معتبر">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputPassword">رمز عبور</label>
            <input type="password" name="Password" class="form-control" id="inputPassword" placeholder="مانند: !example12">
        </div>
        <div class="form-group col-md-6">
            <label for="inputRepeatPassword">تکرار رمز عبور</label>
            <input type="password" name="RepeatPassword" class="form-control" id="inputRepeatPassword" placeholder="رمز عبور خود را تکرار کنید">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="UserRoleSelect">نقش کاربری</label>
            <select class="form-control" name="UserRole" id="UserRoleSelect">
                @foreach($roles as $key => $value)
                    <option value="{{ $value }}">{{ $key }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="UserStatusSelect">وضعیت</label>
            <select class="form-control" name="UserStatus" id="UserStatusSelect">
                @foreach($statuses as $key => $value)
                    <option value="{{ $value }}">{{ $key }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="UserTypeSelect">نوع کاربری</label>
            <select class="form-control" name="UserType" id="UserTypeSelect">
                @foreach($types as $key => $value)
                    <option value="{{ $value }}">{{ $key }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group col-md-6">
        <button type="submit" class="btn btn-primary" >ثبت کاربر</button>
    </div>
</form>

resources/views/admin/users/list.blade.php
@extends('layouts.admin')

@section('wrapper')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Dynamic Table

                    </header>
                    <div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row">
                            <div class="col-sm-6">
                                <div id="sample_1_length" class="dataTables_length"><label><select size="1"
                                                                                                   name="sample_1_length"
                                                                                                   aria-controls="sample_1"
                                                                                                   class="form-control">
                                            <option value="10" selected="selected">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                        </select> records per page</label></div>
                            </div>
                            <div class="col-sm-6">
                                <div class="dataTables_filter" id="sample_1_filter"><label>Search: <input type="text"
                                                                                                          aria-controls="sample_1"
                                                                                                          class="form-control"></label>
                                </div>
                            </div>
                        </div>
                        <table class="table table-striped border-top dataTable" id="sample_1"
                               aria-describedby="sample_1_info">
                            <thead>
                            <tr role="row">
                                <th style="width: 13px;" class="sorting_disabled" role="columnheader" rowspan="1"
                                    colspan="1" aria-label="">
                                    <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes">
                                </th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1"
                                    rowspan="1" colspan="1" aria-label="Username: activate to sort column ascending"
                                    style="width: 179px; ">نام کامل
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label="Email: activate to sort column ascending" style="width: 338px;">ایمیل
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label="Points: activate to sort column ascending" style="width: 124px;">موبایل
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label="Joined: activate to sort column ascending" style="width: 187px;">نقش
                                    کاربری
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label="Joined: activate to sort column ascending" style="width: 187px;">وضعیت
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label="Joined: activate to sort column ascending" style="width: 187px;">موجودی
                                </th>
                                <th class="hidden-phone sorting" role="columnheader" tabindex="0"
                                    aria-controls="sample_1" rowspan="1" colspan="1"
                                    aria-label=": activate to sort column ascending" style="width: 195px;">تاریخ عضویت
                                </th>
                            </tr>
                            </thead>

                            <tbody role="alert" aria-live="polite" aria-relevant="all">
                            @foreach($users[0] as $user)
                                    <tr>
                                        <td class="  sorting_1">
                                            <input type="checkbox" class="checkboxes" value="1">
                                        </td>
                                        <td class=" ">
                                            {{ $user[0]['name'] }}
                                        </td>
                                        <td class="hidden-phone ">
                                            <a href="mailto:jhone-doe@gmail.com">
                                                {{ $user[0]['user_email'] }}
                                            </a>
                                        </td>
                                        <td class="hidden-phone ">
                                            {{ $user[0]['user_mobile'] }}
                                        </td>
                                        <td class="center hidden-phone ">
                                            {{ $user[0]['user_role'] }}
                                        </td>
                                        <td class="hidden-phone ">
                                        <span class="label label-{{ $user[0]['user_status'] == 0 ? 'success' : 'danger' }}">
                                            {{ $user[0]['user_status'] == 0 ? 'غیرفعال' : 'فعال' }}
                                        </span>
                                        </td>
                                        <td class="center hidden-phone ">
                                            0
                                            {{--{{ $user[0]['user_wallet_id'] }}--}}
                                        </td>
                                        <td class="center hidden-phone ">
                                            {{ $user[0]['created_at'] }}
                                        </td>
                                    </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_info" id="sample_1_info">
                                    Showing 1 to 10 of 25 entries
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="dataTables_paginate paging_bootstrap pagination">
                                    {{--<ul>--}}
                                        {{--<li class="prev disabled">--}}
                                            {{--<a href="#">← Prev</a>--}}
                                        {{--</li>--}}
                                        {{--<li class="active">--}}
                                            {{--<a href="#">1</a>--}}
                                        {{--</li>--}}
                                        {{--<li>--}}
                                            {{--<a href="#">2</a>--}}
                                        {{--</li>--}}
                                        {{--<li>--}}
                                            {{--<a href="#">3</a>--}}
                                        {{--</li>--}}
                                        {{--<li class="next">--}}
                                            {{--<a href="#">Next → </a>--}}
                                        {{--</li>--}}
                                    {{--</ul>--}}
                                    {{ $users[1] }}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
@endsection